### ISSUE TITLE
bulid hologres-connector-hive-base  fail

### ISSUE THREAD

**Issue by zhangjiandong-baozi** [aliyun/alibabacloud-hologres-connectors#2]
bulid hologres-connector-hive-base  fail

idea 用install插件打包时说org.scalastyle 报错 ，将tool/scalastyle-config.xml 注释也一样报错，求怎么打包成功

Failed to execute goal org.scalastyle:scalastyle-maven-plugin:1.0.0:check (default) on project hologres-connector-flink-base: Failed during scalastyle execution

![image](https://user-images.githubusercontent.com/52601730/145706309-4fcd493d-f9c5-4d39-ba22-fd172fdb0876.png)

**Comment by zgdgod** [comment]
用mvn打包加上 -Dcheckstyle.skip；或者把maven-checkstyle-plugin插件去掉

**Comment by zhangjiandong-baozi** [comment]
谢谢，flink base已经打包成功

**Comment by zhangjiandong-baozi** [comment]
hologres-connector-flink-1.11  打包又出现了问题？想问问大佬怎么解决？太感谢了
如下：Failure to find com.alibaba.hologres:hologres-connector-parent:pom:1.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced


![image](https://user-images.githubusercontent.com/52601730/145765243-f117e128-cef8-4cc7-aa71-7a7f47f3afa0.png)

**Comment by zhangjiandong-baozi** [comment]
我将
  <parent>
        <groupId>com.alibaba.hologres</groupId>
        <artifactId>hologres-connector-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
注释 直接打包失败

**Comment by zgdgod** [comment]
已经上传到中央仓库，现在可以指定1.0.0版本进行使用；
